# Generated by Django 5.2.5 on 2025-08-12 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(help_text="项目组标题，如 '炸服'", max_length=200)),
                ('title', models.CharField(max_length=200, verbose_name='确认项')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='template_images/', verbose_name='模板图片')),
                ('order', models.PositiveIntegerField(default=0, help_text='用于排序的字段')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
