# Generated by Django 5.2.5 on 2025-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_templateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
