# Generated by Django 5.2.5 on 2025-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_checklisttemplate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='creation_count',
            field=models.PositiveIntegerField(default=0, help_text='记录模板被发布的次数'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='last_created_at',
            field=models.DateTimeField(blank=True, help_text='记录模板最后一次被发布的时间', null=True),
        ),
    ]
